### ISSUE TITLE
Raging Netflix disappeared from Chrome app list

### ISSUE THREAD

**Issue by Gagagma** [zachleat/Raging-Netflix-Queue#13]
I downloaded it a few days ago, had to 'restore' my system (another issue), and now Raging Netflix disappeared from my Chrome apps and the store does not let me add it again.

**Comment by zachleat** [comment]
Yep, this no longer lives on the Chrome store and is not maintained anymore—especially given Netflix’s anti-developer stance on their APIs. You may have some luck downloading the code here and installing it as an unpacked extension locally, however!

Sorry—and good luck!

**Comment by Gagagma** [comment]
Thanks for your answer….I did download it and have had no luck trying to install…I am 81, :), and have been playing with the PC for well over 20 ears, but no go on this one…

It IS in the Chrome store, except it says I have it….just found it a few days ago and was able to use it then…

Netflix is making a big mistake with not allowing us to build up lists easily…

Elaine…

**Comment by zachleat** [comment]
Well, hot damn, Elaine. I’m gonna try and fix this for you—only because you’re such a badass. Please stand by.

**Comment by zachleat** [comment]
Well, after updating the extension it looks like this is not fixable. Sorry Elaine. Netflix has retired the data source I was using.

http://techcrunch.com/2013/03/08/netflix-stops-issuing-api-keys-to-new-developers-effectively-ending-its-developer-program/

So, it is with regret that I must admit that I am unable to fix this on my end. However, this is one of the coolest issues I’ve ever received on GitHub—so thank you for that!

**Comment by Gagagma** [comment]
Thanks for trying, I think Netflix made a huge mistake.

Elaine
